[tool.poetry]
name = "llm-cookbook"
version = "0.1.0"
description = ""
authors = ["He Fei <droxer.he@gmail.com>"]
readme = "README.md"
packages = [{include = "llm-cookbook"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.26.4"
pandas = "^2.2.1"
matplotlib = "^3.8.3"
langchain = "^0.2.3"
phidata = "^2.4.20"
langchain-community = "^0.2.7"
langchain-openai = "^0.1.17"
langchain-experimental = "^0.0.62"
neo4j = "^5.22.0"
pyautogen = "^0.2.32"
transformers = "^4.42.4"
icecream = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
