[project]
name = "llm-cookbook"
version = "0.1.0"
description = "LLM Cookbook"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.1.0",
    "sentence-transformers>=5.1.0",
    "transformers>=4.55.2",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
