[project]
name = "llm-cookbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10"
dependencies = [
    "einops>=0.8.1",
    "langchain-community>=0.3.23",
    "langchain-experimental>=0.3.4",
    "langchain-openai>=0.3.16",
    "markitdown>=0.1.1",
    "mem0ai>=0.1.98",
    "numexpr>=2.10.2",
    "oaieval>=1.0.6",
    "openai>=1.78.0",
    "rich>=14.0.0",
    "sentence-transformers>=4.1.0",
    "tavily-python>=0.7.2",
]
