[tool.poetry]
name = "llm-cookbook"
version = "0.1.0"
description = ""
authors = ["He Fei <droxer.he@gmail.com>"]
readme = "README.md"
packages = [{include = "llm-cookbook"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
pandas = "^2.2.1"
matplotlib = "^3.8.3"
langchain = "^0.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
